### ISSUE TITLE
Generalise return type of `mcmc`

### ISSUE THREAD

**Issue by ocramz** [jtobin/mighty-metropolis#1]
Can't the pipe in `mcmc` sink to a more general mechanism, rather than `IO ()` ?

**Comment by jtobin** [comment]
Done.  I've propagated the same change to the rest of the motley crew of MCMC libs I maintain too.

**Comment by ocramz** [comment]
Thanks @jtobin ; however I must have misunderstood something about the usage model. What if some functions downstream wanted to gather the results in a container?

**Comment by jtobin** [comment]
Ahhh right, I see.  That's doable as-is, but needs some work around it to make things a bit easier.  I was waiting for someone to request this before actually dealing with it; my standard usage model is to literally dump results to disk and examine the chain in R. 😄 

The `Transition` type is a state monad transformer over a probability monad, so you can work with e.g. `metropolis` to build a list of results or what have you in memory using normal combinators for dealing with that kind of thing.  I'll add some documentation and probably a new helper/wrapper function for this.
